Add RecipeUtils.js
OpenBrews/OpenBrews pull request #67
Opened 2016-10-24 19:03 UTC by mbellgb

Amongst other things, `RecipeUtils.js` aims to help fix #61 by calculating IBU and the various gravity values of a recipe. Perhaps it's worth refactoring this file into some smaller files though?

This PR also adds a calcIBU function to `EditRecipeCtrl.js`.

2016-10-24 21:41 UTC, MichaelWashburnJr requested changes
I still have to run through values and compare to existing IBU/OG/FG calculators, but some documentation changes would be nice

2016-10-24 21:41 UTC, mdw7326 commented on openbrews/recipe/RecipeUtils.js
> +    this.ibuFromHop = function (hop, batchSize, gravity) {
Can we extract the magic numbers into constants or at least document them here?

2016-10-24 21:41 UTC, mdw7326 commented on openbrews/recipe/RecipeUtils.js
> +        var gravity = this.boilGravity(recipe, og);
I know this is in the code I linked, but I'm not sure what the difference between boil gravity and og is. Do you know by any chance?

2016-10-24 21:41 UTC, mdw7326 commented on openbrews/recipe/RecipeUtils.js
> +            return acc + (frmtable.weightUnits === 'Kg')? this.kgsToLbs(frmtable.weight) : frmtable.weight;
this is adding lbs to a value where only oz are being added. Is this correct? Does this need to be converted to oz first?

2016-10-24 21:41 UTC, mdw7326 commented on openbrews/recipe/RecipeUtils.js
> +    this.calcBatchSize = function (recipe) {
can we document the units and meaning of this returned value?

2016-10-24 21:41 UTC, mdw7326 commented on openbrews/recipe/RecipeUtils.js
> +        fg = 1 + ((100 - attenuation) / 100) * (og - 1);
can we document what this calculation does?

2016-10-24 21:44 UTC, mdw7326 commented
@mbellgb This looks good so far. I requested some documentation changes, which may be easy or hard to add. Would you consider yourself knowledgeable about the brewing process? If not I can try digging through to find some of the documentation on these things

2016-10-26 10:21 UTC, mbellgb commented on openbrews/recipe/RecipeUtils.js
> +        var gravity = this.boilGravity(recipe, og);
Sadly not, I've been reading up on craft brews as I go along. OG means original gravity I believe, which is the amount of sugar in the recipe _before_ brewing begins.
http://www.brewersfriend.com/2009/02/04/beer-styles-original-gravity-and-final-gravity-chart/

2016-10-26 10:31 UTC, mbellgb commented
@mdw7326 I am not knowledgeable at all about brewing! But I'll try and find out more about some of these processes and equations. First, I'll fix the batchSize calculation and then try to work out what the magic numbers in the `ibuFromHop` method. :)

2016-10-26 10:51 UTC, mbellgb commented on openbrews/recipe/RecipeUtils.js
> +            return acc + (frmtable.weightUnits === 'Kg')? this.kgsToLbs(frmtable.weight) : frmtable.weight;
Good catch, I'll change that now!

2016-10-26 10:51 UTC, mbellgb commented on openbrews/recipe/RecipeUtils.js
> +    this.ibuFromHop = function (hop, batchSize, gravity) {
Sure, I'll see what I can do.

According to [this](http://howtobrew.com/book/section-1/hops/hop-bittering-calculations) page, it seems like the numbers were just 'found' by recording a lot of data and don't really represent anything. I'm not sure we should make them constants or not?

I've included a link to the website as a comment in the code.

2016-10-26 13:18 UTC, mdw7326 commented
@mbellgb Thanks. Don't kill yourself on the documentation requests. I'm planning on at least running a few recipes through [this calculator](http://www.brewersfriend.com/homebrew/recipe/calculator/) and our calculator to compare values. As long as it's working I'll go ahead with the merge. 

It would be awesome if we could add some kind of test framework to this module, and then I could get a large set of test data and run it through. What are your thoughts on that?

2016-10-28 01:55 UTC, mdw7326 commented
I've spent a **lot** of time trying to get this to work today. I don't think the logic is quite right and there's a lot of console errors. I'm not sure this is the right approach

2016-10-28 10:29 UTC, mbellgb commented
@mdw7326 Apologies, I've been trying to find time to work on this outside of uni time. In terms of testing, one option could be to run automated testing with Travis CI? It's free I believe and can run automatically when code is pushed to GitHub.

I'm really sorry this hasn't worked out right and you spent a lot of time trying to fix it... what do you think would have been a better approach?

2016-10-28 13:49 UTC, mdw7326 commented
@mbellgb Yes, travis is awesome. But we would need to write the tests in some framework first, I hear a lot of good things about "karma" tests. I think we should start at the basic cases, like calculating gravity, test, verify, and then build our way up from there slowly.

2016-10-30 14:31 UTC, mbellgb commented
@mdw7326 I've heard Jasmine is actually quite good for testing as well. I found this rather interesting blog post which talks about how to test services by injecting them into the test script. https://nathanleclaire.com/blog/2014/04/12/unit-testing-services-in-angularjs-for-fun-and-for-profit/

2016-11-01 14:39 UTC, mdw7326 commented
I've continued this work in the add-util-service branch. I added karma tests and key function definitions. All are pretty empty right now, I want to start fresh and try tackling one problem at a time using a TDD approach. I've got to define the tests still though.

2016-11-01 14:39 UTC, closed without merging